### PR TITLE
SYS-187 added basic github CI

### PR DESCRIPTION
**Pull request by TieDyedSheep**
Jenkins job trigger will be in a separate PR for SYS-136

### CODE REVIEW

**Comment by chrypnotoad** [comment]
@CodiumAI-Agent /review

**Comment by chrypnotoad** [comment]
@CodiumAI-Agent /improve

**Comment by TieDyedSheep** [comment]
This is blocked pending what appears to be a fix to lib-net for a package-lock.json out of sync issue that's causing this build to fail

**Review by chrypnotoad — APPROVED** [review]

**Comment by TieDyedSheep** [comment]
canceling this in lieu of a more current PR from Daniel

**Pull request closed without merging**
