### PR TITLE
SHARD-1059: set failed response and await claim/penalty tx applies

### PR DESCRIPTION
**Pull request by PudgyPug**

### CODE REVIEW

**Review by devendra-shardeum — APPROVED** [review]
approving this pr.. based on the comment linked in the ticket ( for the requested changes by me ) .. but i think smoke testing will be done by QA team.. or someone else.. i think it's not done on this pr yet..

**Review by urnotsam — APPROVED** [review]

**Comment by Aryan2472** [comment]
nicec suggesion

**Comment by Aryan2472** [comment]
same here

**Comment by samir247247** [comment]
run  to f.a

**Pull request merged**
